# Generated by Django 6.0 on 2025-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS for this post'),
        ),
    ]
