# Generated by Django 6.0 on 2025-12-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_media_post_alter_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='custom_css',
        ),
    ]
